fullnameOverride: twt-admin

image:
  repository: ghcr.io/0xdsqr/tastingswithtay-admin
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-creds

env:
  BASE_URL: https://admin.tastingswithtay.com
  BETTER_AUTH_URL: https://admin.tastingswithtay.com
  DISCORD_CLIENT_ID: "1465977766485688370"
  TRUSTED_ORIGINS: https://admin.tastingswithtay.com,https://tastingswithtay.com

existingSecret: twt-secrets

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: admin.tastingswithtay.com
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi
