/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WineIndexRouteImport } from './routes/wine/index'
import { Route as TestKitchenIndexRouteImport } from './routes/test-kitchen/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as GardenAndFlockIndexRouteImport } from './routes/garden-and-flock/index'
import { Route as WineSlugRouteImport } from './routes/wine/$slug'
import { Route as TestKitchenSlugRouteImport } from './routes/test-kitchen/$slug'
import { Route as RecipesSlugRouteImport } from './routes/recipes/$slug'
import { Route as ApiReadyRouteImport } from './routes/api/ready'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiImagesFolderFileNameRouteImport } from './routes/api/images.$folder.$fileName'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WineIndexRoute = WineIndexRouteImport.update({
  id: '/wine/',
  path: '/wine/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestKitchenIndexRoute = TestKitchenIndexRouteImport.update({
  id: '/test-kitchen/',
  path: '/test-kitchen/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenAndFlockIndexRoute = GardenAndFlockIndexRouteImport.update({
  id: '/garden-and-flock/',
  path: '/garden-and-flock/',
  getParentRoute: () => rootRouteImport,
} as any)
const WineSlugRoute = WineSlugRouteImport.update({
  id: '/wine/$slug',
  path: '/wine/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestKitchenSlugRoute = TestKitchenSlugRouteImport.update({
  id: '/test-kitchen/$slug',
  path: '/test-kitchen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesFolderFileNameRoute = ApiImagesFolderFileNameRouteImport.update({
  id: '/api/images/$folder/$fileName',
  path: '/api/images/$folder/$fileName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/test-kitchen/$slug': typeof TestKitchenSlugRoute
  '/wine/$slug': typeof WineSlugRoute
  '/garden-and-flock/': typeof GardenAndFlockIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/test-kitchen/': typeof TestKitchenIndexRoute
  '/wine/': typeof WineIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/images/$folder/$fileName': typeof ApiImagesFolderFileNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/test-kitchen/$slug': typeof TestKitchenSlugRoute
  '/wine/$slug': typeof WineSlugRoute
  '/garden-and-flock': typeof GardenAndFlockIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/test-kitchen': typeof TestKitchenIndexRoute
  '/wine': typeof WineIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/images/$folder/$fileName': typeof ApiImagesFolderFileNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/test-kitchen/$slug': typeof TestKitchenSlugRoute
  '/wine/$slug': typeof WineSlugRoute
  '/garden-and-flock/': typeof GardenAndFlockIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/test-kitchen/': typeof TestKitchenIndexRoute
  '/wine/': typeof WineIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/images/$folder/$fileName': typeof ApiImagesFolderFileNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/api/health'
    | '/api/ready'
    | '/recipes/$slug'
    | '/test-kitchen/$slug'
    | '/wine/$slug'
    | '/garden-and-flock/'
    | '/recipes/'
    | '/test-kitchen/'
    | '/wine/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/images/$folder/$fileName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/api/health'
    | '/api/ready'
    | '/recipes/$slug'
    | '/test-kitchen/$slug'
    | '/wine/$slug'
    | '/garden-and-flock'
    | '/recipes'
    | '/test-kitchen'
    | '/wine'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/images/$folder/$fileName'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/api/health'
    | '/api/ready'
    | '/recipes/$slug'
    | '/test-kitchen/$slug'
    | '/wine/$slug'
    | '/garden-and-flock/'
    | '/recipes/'
    | '/test-kitchen/'
    | '/wine/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/images/$folder/$fileName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadyRoute: typeof ApiReadyRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  TestKitchenSlugRoute: typeof TestKitchenSlugRoute
  WineSlugRoute: typeof WineSlugRoute
  GardenAndFlockIndexRoute: typeof GardenAndFlockIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  TestKitchenIndexRoute: typeof TestKitchenIndexRoute
  WineIndexRoute: typeof WineIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiImagesFolderFileNameRoute: typeof ApiImagesFolderFileNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wine/': {
      id: '/wine/'
      path: '/wine'
      fullPath: '/wine/'
      preLoaderRoute: typeof WineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-kitchen/': {
      id: '/test-kitchen/'
      path: '/test-kitchen'
      fullPath: '/test-kitchen/'
      preLoaderRoute: typeof TestKitchenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden-and-flock/': {
      id: '/garden-and-flock/'
      path: '/garden-and-flock'
      fullPath: '/garden-and-flock/'
      preLoaderRoute: typeof GardenAndFlockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wine/$slug': {
      id: '/wine/$slug'
      path: '/wine/$slug'
      fullPath: '/wine/$slug'
      preLoaderRoute: typeof WineSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-kitchen/$slug': {
      id: '/test-kitchen/$slug'
      path: '/test-kitchen/$slug'
      fullPath: '/test-kitchen/$slug'
      preLoaderRoute: typeof TestKitchenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$folder/$fileName': {
      id: '/api/images/$folder/$fileName'
      path: '/api/images/$folder/$fileName'
      fullPath: '/api/images/$folder/$fileName'
      preLoaderRoute: typeof ApiImagesFolderFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadyRoute: ApiReadyRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  TestKitchenSlugRoute: TestKitchenSlugRoute,
  WineSlugRoute: WineSlugRoute,
  GardenAndFlockIndexRoute: GardenAndFlockIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  TestKitchenIndexRoute: TestKitchenIndexRoute,
  WineIndexRoute: WineIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiImagesFolderFileNameRoute: ApiImagesFolderFileNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
