apiVersion: v2
name: tastingswithtay-web
description: Helm chart for deploying the Tastings with Tay web application.
type: application
version: 0.1.1
appVersion: "sha-9b036a4f1317c3b7a990c3b1cd98e24258f1a5b9"
