apiVersion: v2
name: tastingswithtay-web
description: Helm chart for deploying the Tastings with Tay web application.
type: application
version: 0.1.1
appVersion: "sha-ebc7b5e3cdf0113b4346e167ef9609598306e7ae"
