apiVersion: v2
name: tastingswithtay-web
description: Helm chart for deploying the Tastings with Tay web application.
type: application
version: 0.1.1
appVersion: "sha-3154b87abf9a3134dd6e8047bbc4568a83fe0042"
