fullnameOverride: twt-web

image:
  repository: ghcr.io/0xdsqr/tastingswithtay-web
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-creds

env:
  BASE_URL: https://tastingswithtay.com
  CDN_BASE: https://cdn.dsqr.dev
  DISCORD_CLIENT_ID: "1465977766485688370"
  S3_BUCKET: tastingswithtay
  S3_ENDPOINT: s3.dsqr.dev
  S3_FORCE_PATH_STYLE: "true"
  S3_REGION: us-east-1
  S3_USE_SSL: "true"
  TRUSTED_ORIGINS: https://tastingswithtay.com
  OTEL_SERVICE_NAME: twt-web
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.observability.svc.cluster.local:4318
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector.observability.svc.cluster.local:4318/v1/traces
  OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
  OTEL_RESOURCE_ATTRIBUTES: deployment.environment=prod,k8s.namespace.name=twt

existingSecret: twt-secrets

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: tastingswithtay.com
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi
